services:
  db:
    image: mysql:8
    container_name: my_sql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "6603:3306"
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysql -u root -proot -e 'USE test;'"]
      interval: 20s
      timeout: 30s
      retries: 10

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    container_name: my_backend
    ports:
      - "8800:8800"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend