services:
  db:
    image: mysql:5
    container_name: my_sql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_backend
    ports:
      - "8800:8800"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend